import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Image from 'next/image';
import { Theme } from '@radix-ui/themes';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Theme appearance={'light'}>
          <section className={'fixed inset-0'}>
            <Image
              src={'/assets/backgrounds/Flow 2.jpg'}
              alt={'Background Image'}
              width={1920}
              height={1080}
              className={'absolute size-full object-cover'}
            />
          </section>

          {children}
        </Theme>
      </body>
    </html>
  );
}
